### PR TITLE
Default statusCode to 200 like node does.

### PR DESCRIPTION
**Pull request by Raynos**

### CODE REVIEW

**Comment by Raynos** [comment]
Can you release a new version on npm ?

**Comment by Raynos** [comment]
better yet, can you add me as a collaborator and give me npm access. I would like to maintain this.

**Comment by tommymessbauer** [comment]
Both great ideas.  So yes.  Adding now.

**Comment by tommymessbauer** [comment]
I am bumping the major version due to the passthrough stream addition.  Will be published momentarily.

**Comment by Raynos** [comment]
@tommymessbauer thanks :)

**Pull request merged**
